trigger:
  branches:
    include:
    - master
  paths:
    include:
    - jobs.yml

pool:
  vmImage: ubuntu-latest

stages:
- stage: IaC
  displayName: Create Azure Environment Pipeline
  jobs:
  - template: jobs.yml
    parameters:
      PIPE: Create
